version: "3.8"
services:

  client-prod:
    build: 
      context: ./js
      dockerfile: Dockerfile.prod
    ports:
    - "3000:80"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.prod
    environment:
    - BTC_SERVER=btc-server:8080
  
  btc-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
    - REDIS_URL=redis:6379
    - CRYPTO_COMPARE_URL=https://min-api.cryptocompare.com/data/pricemulti?fsyms=BTC,ETH,DOGE&tsyms=USD,EUR
    volumes:
    - ./server/redis-creds:/mnt/secrets-store/redis

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
