version: "3.8"
services:

  client-prod:
    build: 
      context: ./js
      dockerfile: Dockerfile.prod
    ports:
    - "3000:80"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.prod
    environment:
    - BTC_SERVER=btc-server:8080
  
  btc-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
    - REDIS_URL=redis:6379
    - CRYPTO_API_KEY=${CRYPTO_API_KEY}
    - CRYPTO_THREE_URL=https://min-api.cryptocompare.com/data/pricemulti?fsyms=BTC,ETH,DOGE&tsyms=USD,EUR
    - CRYPTO_BTC_MONTHLY=https://min-api.cryptocompare.com/data/v2/histoday?fsym=BTC&tsym=USD&limit=31
    - CRYPTO_ETH_MONTHLY=https://min-api.cryptocompare.com/data/v2/histoday?fsym=ETH&tsym=USD&limit=31
    - CRYPTO_DOGE_MONTHLY=https://min-api.cryptocompare.com/data/v2/histoday?fsym=DOGE&tsym=USD&limit=31
    volumes:
    - ./server/redis:/mnt/secrets-store/redis

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
