version: "3.8"
services:

  client-dev:
    build: 
      context: ./js
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    volumes:
    - ./js/src:/app/src
    environment:
    - REACT_APP_DOCKER_ENV=true

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
    - BTC_SERVER=btc-server:8080
    ports:
    - "8081:8081"

  btc-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
    - REDIS_URL=redis:6379
    - CRYPTO_COMPARE_URL=https://min-api.cryptocompare.com/data/pricemulti?fsyms=BTC,ETH,DOGE&tsyms=USD,EUR
    volumes:
    - ./server/redis-creds:/mnt/secrets-store/redis

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
