apiVersion: v1
kind: ConfigMap
metadata:
  name: urls
data:
  REDIS_URL: redis:6379
  SERVER_URL: server:8080
  CRYPTO_THREE_URL: "https://min-api.cryptocompare.com/data/pricemulti?fsyms=BTC,ETH,DOGE&tsyms=USD,EUR"
  CRYPTO_BTC_MONTHLY: "https://min-api.cryptocompare.com/data/v2/histoday?fsym=BTC&tsym=USD&limit=31"
  CRYPTO_ETH_MONTHLY: "https://min-api.cryptocompare.com/data/v2/histoday?fsym=ETH&tsym=USD&limit=31"
  CRYPTO_DOGE_MONTHLY: "https://min-api.cryptocompare.com/data/v2/histoday?fsym=DOGE&tsym=USD&limit=31"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    masterauth password
    requirepass password
    dir /data
    dbfilename dump.rdb
    appendonly yes
    appendfilename "appendonly.aof"
    protected-mode no
    port 6379
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: vault-bootstrap
#   namespace: vault
# data:
#   bootstrap.sh: |
#     {
#       vault status
#       while [[ $? -ne 2 ]]; do sleep 1 && vault status; done
#     } > /dev/null

#     vault operator init --key-shares=1 --key-threshold=1 > /tmp/vault_init
#     unseal=$(cat /tmp/vault_init | grep "Unseal Key 1: " | awk '{print $4}')
#     root=$(cat /tmp/vault_init | grep "Initial Root Token:" | awk '{print $4}')
#     vault operator unseal ${unseal?} > /dev/null
#     vault login ${root?} > /dev/null