apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-hpa
  namespace: btc-charts

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway-deployment
  minReplicas: 4
  maxReplicas: 20
  targetCPUUtilizationPercentage: 75