apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-bootstrap
data:
  bootstrap.sh: |
    {
      vault status
      while [[ $? -ne 2 ]]; do sleep 1 && vault status; done
    } > /dev/null

    vault operator init --key-shares=1 --key-threshold=1 > /tmp/vault_init
    unseal=$(cat /tmp/vault_init | grep "Unseal Key 1: " | awk '{print $4}')
    root=$(cat /tmp/vault_init | grep "Initial Root Token:" | awk '{print $4}')
    vault operator unseal ${unseal?} > /dev/null
    vault login ${root?} > /dev/null